[build]
  base = "rupantaran"  
  command = "pip install -r requirements.txt && sphinx-build -b html docs/ docs/_build/html"
  publish = "docs/_build/html"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"  
  PYTHON_VERSION = "3.9" 

[context.production]
  deploy_log_visibility = "public"

[context.deploy-preview]
  build_status = "active"