name: Deploy to PyPI (Production)

on:
  pull_request:
    branches:
      - main  # Runs only when a feature branch is merged into main
    types:
      - closed

jobs:
  build-and-publish-pypi:
    if: github.event.pull_request.merged == true  # Ensures only merged PRs trigger deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          rm -rf dist/
          python -m build

      - name: Check package validity
        run: twine check dist/*

      - name: Publish to PyPI (Production)
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PROD_API_TOKEN }}
