name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Runs only when changes are pushed to the main branch
    paths:
      - "docs/**"  # Runs only when files in the docs folder are modified

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4  # ✅ Updated to v4
        with:
          path: docs/_build/html  # The output folder of Sphinx build

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # ✅ Updated to v4
