name: Deploy Python Package

on:
  push:
    tags:
      - "v*"  # Deploy to TestPyPI when a version tag is pushed to a feature branch
  pull_request:
    branches:
      - main  # Deploy to PyPI when a feature branch is merged into main
    types:
      - closed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine packaging requests

      - name: Get Package Version
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected package version: $VERSION"

      - name: Check Existing Version on TestPyPI
        if: startsWith(github.ref, 'refs/tags/v') && startsWith(github.ref, 'refs/heads/feature/')
        run: |
          PACKAGE_NAME=$(python setup.py --name)
          RESPONSE=$(curl -s https://test.pypi.org/pypi/$PACKAGE_NAME/json || echo "{}")
          EXISTING_VERSION=$(echo $RESPONSE | python -c "import sys, json; print(json.loads(sys.stdin.read()).get('info', {}).get('version', '0.0.0'))")
          echo "Existing TestPyPI version: $EXISTING_VERSION"
          if [ "$(python -c 'from packaging.version import parse; print(parse("'$PACKAGE_VERSION'") > parse("'$EXISTING_VERSION'"))')" == "False" ]; then
            echo "Version $PACKAGE_VERSION is not greater than $EXISTING_VERSION. Skipping upload."
            exit 1
          fi

      - name: Check Existing Version on PyPI
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          PACKAGE_NAME=$(python setup.py --name)
          RESPONSE=$(curl -s https://pypi.org/pypi/$PACKAGE_NAME/json || echo "{}")
          EXISTING_VERSION=$(echo $RESPONSE | python -c "import sys, json; print(json.loads(sys.stdin.read()).get('info', {}).get('version', '0.0.0'))")
          echo "Existing PyPI version: $EXISTING_VERSION"
          if [ "$(python -c 'from packaging.version import parse; print(parse("'$PACKAGE_VERSION'") > parse("'$EXISTING_VERSION'"))')" == "False" ]; then
            echo "Version $PACKAGE_VERSION is not greater than $EXISTING_VERSION. Skipping upload."
            exit 1
          fi

      - name: Build package
        run: |
          rm -rf dist/  # Ensure a clean build
          python -m build

      - name: Check package validity
        run: twine check dist/*

      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/v') && startsWith(github.ref, 'refs/heads/feature/')
        run: twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN }}

      - name: Publish to PyPI (Production)
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PROD_API_TOKEN }}
